### ISSUE TITLE
unexpected keyword argument

### ISSUE THREAD

**Issue by jlblancopastor** [kgori/treeCl#13]
when running treeCl with these options:
treeCl -i input -f fasta --trees_in trees -r 100 -c mds -m geo -g ml -d dna -o output -t temp -u 11 -a

I get a keyword argument error

> Using temporary directory temp
> Loading input files
> Traceback (most recent call last):
>   File "/home/jlblancopast/git/treeCl/bin/treeCl", line 443, in <module>
>     debug=args.e,
> TypeError: __init__() got an unexpected keyword argument 'compression'

It seems that there is a bug in the code

**Comment by cpouchon** [comment]
Hi, 
I am getting the same error message, and I can't run treeCl directly from ipython console as indicated in your "Example Analysis".

**Comment by kgori** [comment]
@jlblancopastor Thanks for letting me know. The command line interface expects an older version of the library. I'll bring it up to date.

**Comment by kgori** [comment]
@cpouchon could you give me the details of the error you get when running from the IPython console?

**Comment by kdebray** [comment]
Hi, 
I also get the keyword argument error. Has this bug been fixed ?
```
Using temporary directory ./temp3/
Loading input files
Traceback (most recent call last):
  File "treeCl", line 443, in <module>
    debug=args.e,
TypeError: __init__() got an unexpected keyword argument 'compression'
```

**Comment by Arraiano-Castilho** [comment]
Hi, any advance here? I'm having the same issue. 

Using temporary directory Temp
Loading input files
Traceback (most recent call last):
  File "/home/user/Software/treeCL/treeCl/bin/treeCl", line 443, in <module>
    debug=args.e,
TypeError: __init__() got an unexpected keyword argument 'compression'

Cheers,
RAC
